mysite/enquetes/urls.py
from django.urls import path
from . import views

app_name = 'enquetes'
urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    path('<int:pk>/', views.DetalhesView.as_view(), name="detalhes"),
    path('<int:pk>/resultado/', views.ResultadoView.as_view(), name="resultado"),
    path('<int:enquete_id>/votacao/', views.VotacaoView.as_view(), name="votacao"),
]

mysite/financeapp/urls.py
from django.urls import path
from . import views

app_name = 'financeapp'
urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    path('<int:pk>/', views.DetalhesView.as_view(), name="detalhes"),
]

mysite/main/urls.py
from django.urls import path
from . import views

app_name ='main'
urlpatterns = [
    path('',views.index,name="index"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include('main.urls')),
    path('enquetes/',include('enquetes.urls')),
    path('financeapp/',include('financeapp.urls')),
    path('admin/', admin.site.urls),
]

mysite/main/models.py
from django.db import models

# Create your models here.

mysite/main/views.py
from django.shortcuts import render
# Create your views here.

def index(request):
    return render(request, 'main/index.html')

mysite/main/templates/main/index.html
<html>
    <head>
        <title>jonathanIFRNflemerson</title>
    </head>
    <body>
        <h1>Aplicações de jonathanIFRNflemerson</h1>
        <h4>Selecione o App:</h4>
        <ul>
            <li><a href = '{% url 'enquetes:index' %}'>Aplicação Enquetes</a></li>
            <li><a href ='{% url 'financeapp:index' %}'>Aplicação FinanceApp</a></li>
        </ul>

    </body>
</html>