mysite/enquetes/urls.py
from django.urls import path
from . import views

app_name = 'enquetes'
urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    path('<int:pk>/', views.DetalhesView.as_view(), name="detalhes"),
    path('<int:pk>/resultado/', views.ResultadoView.as_view(), name="resultado"),
    path('<int:enquete_id>/votacao/', views.VotacaoView.as_view(), name="votacao"),
]

mysite/main/urls.py
from django.urls import path
from . import views

app_name ='main'
urlpatterns = [
    path('',views.index,name="index"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include('main.urls')),
    path('enquetes/',include('enquetes.urls')),
    path('financeapp/',include('financeapp.urls')),
    path('admin/', admin.site.urls),
]

mysite/enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone

#### novos modelos de extensão do app#######
############################################

class Rotulo(models.Model):
    titulo = models.CharField(max_length=25)
    def __str__(self):
        return self.titulo

class Perfil(models.Model):
    descricao = models.CharField(max_length=100)
    cidade = models.CharField(max_length=20)
    pais_nacionalidade = models.CharField(max_length=20)
    generos = models.TextField()
    class Meta:
        verbose_name_plural = 'Perfis'

class Autor(models.Model):
    nome = models.CharField(max_length=30)
    idade = models.IntegerField()
    perfil = models.OneToOneField(Perfil, on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = 'Autores'
    def __str__(self):
        return self.nome


##### primeiros modelos da aplicação######
##########################################
class Pergunta(models.Model):
    texto = models.CharField(max_length = 200)
    data_publicacao = models.DateTimeField('Data de publicação')
    rotulos = models.ManyToManyField(Rotulo)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE, null = True)
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1)<=self.data_publicacao<=agora
    publicada_recentemente.admin_order_field = 'data_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'Foi publicada recentemente?'

class Opcao(models.Model):
    texto = models.CharField(max_length = 100)
    votos = models.IntegerField(default = 0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Opção'
        verbose_name_plural = 'Opções'

    def __str__(self):
        return self.texto

mysite/enquetes/views.py
from django.shortcuts import render, get_object_or_404, Http404
from django.http import HttpResponseRedirect
from .models import Pergunta, Opcao
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.




class IndexView(generic.View):
    def get(self, request,*args,**kargs):
        ultimas_enquetes = Pergunta.objects.filter(
            data_publicacao__lte = timezone.now()
            ).order_by('-data_publicacao')[:5]
        contexto = { 'ultimas_enquetes': ultimas_enquetes }
        return render(request, 'enquetes/index.html', contexto)

class DetalhesView(generic.View):
    def get(self, request, *args, **kwargs):
        enquete_id = self.kwargs['pk']
        enquete = get_object_or_404(Pergunta, pk = enquete_id)
        agora = timezone.now()
        if enquete.data_publicacao > agora:
           raise Http404('Enquete inexistente')
        return render(request, 'enquetes/pergunta_detail.html', {'pergunta':enquete})


class ResultadoView(generic.View):
    def get(self, request, *args, **kwargs):
        enquete_id = self.kwargs['pk']
        enquete = get_object_or_404(Pergunta, pk =enquete_id)
        return render(request, 'enquetes/resultado.html', {'enquete':enquete})

class VotacaoView(generic.View):
    def post(self, request, *args, **kwargs):
        enquete_id = self.kwargs['enquete_id']
        enquete = get_object_or_404(Pergunta, pk=enquete_id)
        try:
            op_desejada = enquete.opcao_set.get(pk=request.POST['opcao'])
        except (KeyError, Opcao.DoesNotExist):
            contexto = {
                        'enquete':enquete,
                        'error_message': "Deve selecionar antes uma opção valida",
                        }
            return render(request, 'enquetes/detalhes.html/', contexto)
        else:
            op_desejada.votos += 1.0
            op_desejada.save()
            return HttpResponseRedirect(reverse('enquetes:resultado', args = (enquete.id,)))


'''
##### Outras opções para os elementos de views #######
'''

'''
def index(request):
    ultimas_enquetes = Pergunta.objects.order_by('-data_publicacao')[:5]
    contexto = { 'ultimas_enquetes': ultimas_enquetes }
    return render(request, 'enquetes/index.html', contexto)


class IndexView(generic.ListView):
    template_name = 'enquetes/index.html'
    context_object_name = 'ultimas_enquetes'
    def get_queryset(self):
        return Pergunta.objects.order_by('-data_publicacao')[:5]
'''

'''
def detalhes(request, enquete_id):
    enquete = get_object_or_404(Pergunta, pk = enquete_id)
    return render(request, 'enquetes/detalhes.html', {'enquete':enquete})
'''
'''
class DetalhesView(generic.DetailView):
      model = Pergunta
      context_object_name = 'enquete'
      template_name = 'enquetes/detalhes.html'


class DetalhesView(generic.DetailView):
    model = Pergunta
'''

'''
def resultados(request, enquete_id):
    enquete = get_object_or_404(Pergunta, pk = enquete_id)
    return render(request, 'enquetes/resultado.html', {'enquete':enquete})


class ResultadoView(generic.DetailView):
      model = Pergunta
      context_object_name = 'enquete'
      template_name = 'enquetes/resultado.html'
'''
'''
    def votacao(request, enquete_id):
        enquete = get_object_or_404(Pergunta, pk = enquete_id)
        try:
            op_desejada = enquete.opcao_set.get(pk=request.POST['opcao'])
        except (KeyError, Opcao.DoesNotExist):
            contexto = {
                        'enquete':enquete,
                        'error_message': "Deve selecionar antes uma opção valida",
                        }
            return render(request, 'enquetes/detalhes.html/', contexto)
        else:
            op_desejada.votos += 1.0
            op_desejada.save()
            return HttpResponseRedirect(reverse('enquetes:resultado', args = (enquete.id,)))
'''

mysite/enquetes/templates/enquetes/detalhes.html
<html>
    <head>
        <title>App enquete</title>

    </head>
    <body>
        <h2>Aplicação de enquete</h2>
        <h4>Detalhes da enquete #{{enquete.id}}<br/>
        (<i>{{ enquete.data_publicacao }}</i>)</h4>
        <h4>{{enquete.texto}}</h4>
        Escolha a sua opção:
        {% if error_message %}
           <p><strong>{{error_message}}</strong></p>
        {% endif %}
        <form action="{% url 'enquetes:votacao' enquete.id %}" method="post">
            {% csrf_token %}
            {% for op in enquete.opcao_set.all %}
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" name="opcao" id= "opcao{{ forloop.counter }}" value="{{op.id}}"/>
                <label for="opcao{{ forloop.counter }}">{{op.texto}}</label><br/>
            {% endfor %}
            <p><input type="submit" value="Enviar voto" /></p>
        </form>
    </body>
</html>

mysite/enquetes/templates/enquetes/index.html
{%load static%}
<html>
     <head>
         <title>Enquetes App</title>
         <link rel="stylesheet" type="text/css" href="{% static 'enquetes/style.css' %}"/>
     </head>

     <body>
         <h2>Aplicação de enquetes</h2>
         <hr/>
         {% if ultimas_enquetes %}
             <ul>
                {% for enq in ultimas_enquetes %}
                   <li><a href = "{%  url 'enquetes:detalhes' enq.id %}">{{ enq.texto }}</a></li>
                {% endfor %}
             </ul>
         {% else %}
            <p>Nenhuma pergunta cadastrada.</p>
         {% endif %}
         <hr/>
         <a href = "{% url 'main:index' %}"><img src = "{% static 'enquetes/images/setahome.png' %}"/></a>
         <hr>
            <img src = "{% static 'enquetes/images/jovemqueixo.png' %}"/>
         <hr/>

     </body>
</html>

mysite/enquetes/templates/enquetes/pergunta_detail.html
{% load static %}
<html>
    <head>
        <title>App enquete</title>
        <link rel="stylesheet" type="text/css" href="{% static 'enquetes/style.css' %}"/>

    </head>
    <body>
        <h2>Aplicação de enquete</h2>
        <h4>Detalhes da enquete #{{pergunta.id}}<br/>
        (<i>{{ pergunta.data_publicacao }}</i>)</h4>
        <h4>{{pergunta.texto}}</h4>
        Escolha a sua opção:
        {% if error_message %}
           <p><strong>{{error_message}}</strong></p>
        {% endif %}
        <form action="{% url 'enquetes:votacao' pergunta.id %}" method="post">
            {% csrf_token %}
            {% for op in pergunta.opcao_set.all %}
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" name="opcao" id= "opcao{{ forloop.counter }}" value="{{op.id}}"/>
                <label for="opcao{{ forloop.counter }}">{{op.texto}}</label><br/>
            {% endfor %}
            <p><input type="submit" value="Enviar voto" /></p>
        </form>
    </body>
</html>

mysite/enquetes/templates/enquetes/resultado.html
{%load static%}
<html>
    <head>
        <title>App enquete</title>
        <link rel="stylesheet" type="text/css" href="{% static 'enquetes/style.css' %}"/>
    </head>
    <body>
        <h2>Aplicação de enquete</h2>
        <h4>resultados da enquete #{{enquete.id}}<br/>
        (<i>{{ enquete.data_publicacao }}</i>)</h4>
        <h4>{{enquete.texto}}</h4>
        Total de votos por opção:
        <ul>
        {% for op in enquete.opcao_set.all %}
            <li>{{op.texto}} = {{op.votos}} voto{{op.votos|pluralize}}</li><br/>
        {% endfor %}
        </ul>
        <hr/>
        <a href ="{% url 'enquetes:detalhes' enquete.id%}">Voltar novamente</a>
        | <a href = '{% url 'enquetes:index'  %}'>Enquetes</a>
    </body>
</html>