mysite/financeapp/urls.py
from django.urls import path
from . import views

app_name = 'financeapp'
urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    path('<int:pk>/', views.DetalhesView.as_view(), name="detalhes"),
]

mysite/main/urls.py
from django.urls import path
from . import views

app_name ='main'
urlpatterns = [
    path('',views.index,name="index"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include('main.urls')),
    path('enquetes/',include('enquetes.urls')),
    path('financeapp/',include('financeapp.urls')),
    path('admin/', admin.site.urls),
]

mysite/financeapp/models.py
from django.db import models
from django.db.models import Max

# Create your models here.
class Usuario(models.Model):
    nome = models.CharField(max_length = 100)
    def __str__(self):
        return self.nome

class Receita(models.Model):
    servico = models.CharField(max_length = 100)
    salario = models.FloatField(default = 0)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    def __str__(self):
        return self.servico


class DespesaFixa(models.Model):
    despesa = models.CharField(max_length = 100)
    valor = models.FloatField(default = 0)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    def __str__(self):
        return self.despesa

class DespesaEventual(models.Model):
    despesa = models.CharField(max_length = 100)
    valor = models.FloatField(default = 0)
    tempo_divida_mes = models.IntegerField(default = 0)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    def __str__(self):
        return self.despesa

mysite/financeapp/views.py
from django.shortcuts import render, get_object_or_404, Http404
from django.http import HttpResponseRedirect
from .models import Usuario, Receita, DespesaFixa,DespesaEventual
from django.urls import reverse
from django.views import generic
from django.utils import timezone
# Create your views here.
'''
def index(resquest):
    resposta = "<h2>Finance App</h2>"
    return HttpResponse(resposta)
'''

class IndexView(generic.View):
    def get(self, request,*args,**kargs):
        usuarios = Usuario.objects.all()
        contexto = { 'usuarios': usuarios }
        return render(request, 'financeapp/index.html', contexto)

class DetalhesView(generic.View):
    def get(self, request, *args, **kwargs):
        usuario_id = self.kwargs['pk']
        usuario = get_object_or_404(Usuario, pk = usuario_id)
        return render(request, 'financeapp/usuario_detail.html', {'usuario':usuario})

mysite/financeapp/templates/financeapp/index.html
{%load static%}
<html>
     <head>
         <title>FinanceappApp</title>
     </head>

     <body>
         <h2>Controle de finanças</h2>
         Usuários cadastrados:
         <hr/>
         {% if usuarios %}
             <ul>
                {% for user in usuarios %}
                   <li><a href = "{%  url 'financeapp:detalhes' user.id %}">{{ user.nome }}</a></li>
                {% endfor %}
             </ul>
         {% else %}
            <p>Nenhum usuário cadastrado.</p>
         {% endif %}
         <hr/>
         <a href = "{% url 'main:index' %}">Voltar</a>
         <hr>
            <img src = "{% static 'financeapp/images/money.png' %}"/>
         <hr/>

     </body>
</html>

mysite/financeapp/templates/financeapp/usuario_detail.html
<html>

    <head>
        <title>FinanceApp</title>
    </head>

    <body>
        <h2>FinanceApp</h2>
        <h3>Detalhes financeiros do usuário {{usuario.nome}}</h4>
        <hr>
            <h4>Receitas do usuário</h4>
            {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
            {% endif %}
            {% for rec in usuario.receita_set.all %}
                <ul>
                    <li>Serviço: {{rec.servico}}</li>
                    <li>Salario: {{rec.salario}}</li>
                </ul>
            {% endfor %}
        <hr/>
        <hr>
            <h4>Despesas fixas</h4>
            {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
            {% endif %}
            {% for des in usuario.despesafixa_set.all %}
                <ul>
                    <li>Despesa: {{des.despesa}}</li>
                    <li>Valor: {{des.valor}}</li>
                </ul>
            {% endfor %}
        <hr/>
        <hr>
            <h4>Despesas Eventuais</h4>
            {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
            {% endif %}
            {% for des in usuario.despesaeventual_set.all %}
                <ul>
                    <li>Despesa: {{des.despesa}}</li>
                    <li>Valor: {{des.valor}}</li>
                    <li>Prestações: {{des.tempo_divida_mes}}</li>
                </ul>
            {% endfor %}
        <hr/>
        <a href = "{% url 'main:index' %}">Voltar</a>


    </body>
</html>